<img style="float: left;" src="earth-lab-logo-rgb.png" width="150" height="150" />

# Earth Analytics Education - Bootcamp Course Fall 2020

## Important  - Assignment Guidelines

1. Before you turn in your assignment, make sure to run the entire notebook with a fresh kernel. To do this first, **restart the kernel** (in the menubar, select Kernel$\rightarrow$Restart & Run All)
2. In the cells below you will replace the `raise NotImplementedError()` code with your code that addresses the activity challenge. If you don't replace that code, your notebook will not run properly.

```
# YOUR CODE HERE
raise NotImplementedError()
```

3. Any open ended questions will have a "YOUR ANSWER HERE" within a markdown cell. Replace that text with your answer also formatted using Markdown.
4. **IMPORTANT: DO NOT RENAME THIS NOTEBOOK!** If the file name changes, the autograder will not grade your assignment properly.
5. **Do not rename the notebook file.** If you do, the autograder will not recognize your submisson.
6. When you plot, please comment out `plt.show()` as the code below will effectively run `plt.show()` for you and also will grab your plot for autograding. DO NOT DELETE any code that says `DO NOT REMOVE LINE BELOW`. That code is for autograding!!

```
### DO NOT REMOVE LINE BELOW ###
student_plot1_ax = nb.convert_axes(plt)
```



## Follow to PEP 8 Syntax Guidelines

* Run the `autopep8` tool on all cells prior to submitting (HINT: hit shift + the tool to run it on all cells at once!
* Use clear and expressive names for variables. 
* Organize your code to support readability.
* Check for code line length
* Use comments and white space sparingly where it is needed

### Add Your Name Below 
**Your Name:** Judith Ament

<img style="float: left;" src="colored-bar.png"/>

---

# Week 9 Homework Template - Modular Code and Functions

To complete assignment 9, be sure to <a href="https://www.earthdatascience.org/courses/intro-to-earth-data-science/write-efficient-python-code/functions-modular-code/" target="_blank">review  the chapter on functions in the Intro to Earth Data Science online textbook</a> online textbook.

## Assignment Data

For this assignment, you will write **Python** pseudo code, and later **Python** functions, to download and work with multiple datasets. The primary dataset you will use can be downloadoed using **this url: https://ndownloader.figshare.com/files/25033508**: 

In this download, you'll see three directories with files containing data by year:

* ca-fires-yearly/monthly-fire-count
    * The dataset contains the total number of fires (greater than 100 acres) that occurred in each month and year in California between 1992 and 2015. The data are organized with a file for each year from 1992 to 2015.
* ca-fires-yearly/monthly-mean-size
    * The dataset contains the mean fire size (acres) of all fires greater than 100 acres for each month and year in California between 1992 and 2015. The data are organized with a file for each year from 1992 to 2015
* ca-fires-yearly/1992-2015-gt-100-acres
    * The dataset contains the cause of all fires greater than 100 acres in California between 1992 and 2015. The data are organized with a file for each year from 1992 to 2015

Other data used includes average monthly maximum temperatures (Fahrenheit) for the Sonoma County Airport and San Diego area in California between 1999 and 2018 provided by <a href="https://w2.weather.gov/climate/xmacis.php?wfo=mtr" target="_blank">the National Weather Service</a>.

In [60]:
# Core imports needed for grading - Do not modify this cell!
import matplotcheck.notebook as nb
from matplotcheck.base import PlotTester

## Practice Pseudo-coding

In the Markdown cell below, answer the following questions using any kind of Markdown list.

For this assignment, you will need to:

1. open up a group of `.csv` files in a directory, 
2. extract the year from the `.csv` file name and add it to a new column in the `DataFrame`
3. store each DataFrame into a list object using `obj-name.append()`
4. create a single pandas `DataFrame` containing all of the data in all .csv files.
5. plot the data in that `DataFrame`. 

Write  pseudo code that outlines the steps needed to complete the task above. 
Do not use actual code to complete this task. Rather, write down each step using a 
markdown list and using plain english words. 

As you are writing your pseudocode, consider how you could make each part of the workflow
generic enough to accept any set of `.csv` files that could be opened using Pandas.

for file in list
- year = re search numbers dot csv filename group 1
- pandas read csv file df
- df new column is year
- df list append df

df concat 

plot

<img style="float: left;" src="colored-bar.png"/>

## Import Python Packages

In the cell below, add code **after the line for `Your Code Here`**, replacing `raise NotImplementedError()` with your code to import the package/module needed to:
* create plots
* set your working directory
* download data using earthpy functions
* work with numpy arrays

Be sure to list the package imports following the appropriate PEP 8 order and 
spacing requirements.

In [61]:
# YOUR CODE HERE
import os
from glob import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import earthpy as et

In [62]:
# Test package imports - DO NOT MODIFY THIS CELL!
import_answer_points = 0

try:
    pd.NA
    print("\u2705 Score! Pandas has been imported as a pd!")
    import_answer_points += 1
except NameError:
    print("\u274C Pandas has not been imported as a pd, please make sure to import is properly.")

try:
    glob('~')
    print("\u2705 Cool! Glob was imported from glob!")
    import_answer_points += 1
except NameError:
    print("\u274C Glob has not been imported from glob, please make sure to import this properly.")

try:
    plt.show()
    print("\u2705 Nice! matplotlib.pyplot has been imported as plt!")
    import_answer_points += 1
except NameError:
    print("matplotlib.pyplot has not been imported as plt, please make sure to import this properly.")

try:
    os.getcwd()
    print("\u2705 Great work! The os module has imported correctly!")
    import_answer_points += 1
except NameError:
    print("\u274C Oops make sure that the os package is imported.")

try:
    data = et.io
    print("\u2705 Score! The earthpy package has imported correctly!")
    import_answer_points += 1
except NameError:
    print("\u274C Oops make sure that the earthpy package is imported using the alias et.")

print("\n \u27A1 You received {} out of 5 points.".format(import_answer_points))

import_answer_points

✅ Score! Pandas has been imported as a pd!
✅ Cool! Glob was imported from glob!
✅ Nice! matplotlib.pyplot has been imported as plt!
✅ Great work! The os module has imported correctly!
✅ Score! The earthpy package has imported correctly!

 ➡ You received 5 out of 5 points.

5

## Set Working Directory

In the cell below complete the following task:

* **Use a conditional statement** to:
    * Set the working directory to the **`earth-analytics/data` directory in your home directory** if the path exists.
    * Print a helpful message if the path does not exist. 
* **Use reusable variable(s) to reduce repetition in your code.**
* Use the `os` package to ensure that the paths you create will run successfully on any operating system.

In [63]:
# YOUR CODE HERE
data_path = os.path.join(et.io.HOME, "earth-analytics", "data")

if os.path.exists(data_path):
    os.chdir(data_path)
else:
    print("Path data path does not exist")

## Download Data Using EarthPy

In the cell below use **EarthPy** to download **this url: https://ndownloader.figshare.com/files/25033508**:

In [64]:
# YOUR CODE HERE
url = "https://ndownloader.figshare.com/files/25033508"

data_file_path = et.data.get_data(url = url)

In [65]:
# DO NOT MODIFY THIS CELL
# Tests that the working directory is set to earth-analytics/data

path = os.path.normpath(os.getcwd())
student_wd_parts = path.split(os.sep)

wd_points = 0

if student_wd_parts[-2:] == ['earth-analytics', 'data']:
    print("\u2705 Great - it looks like your working directory is set correctly to ~/earth-analytics/data")
    wd_points += 5
else:
    print("\u274C Oops, the autograder will not run unless your working directory is set to earth-analytics/data")

print("\n \u27A1 You received {} out of 5 points for setting your working directory.".format(
    wd_points))
wd_points

✅ Great - it looks like your working directory is set correctly to ~/earth-analytics/data

 ➡ You received 5 out of 5 points for setting your working directory.

5

<img style="float: left;" src="colored-bar.png"/>

## Function Challenge 1: Define Function to Import Data into Pandas

In the cell below create a function that opens and converts a single csv file into a 
Pandas DataFrame with a Year column. The function should have the following properties.

1. Parameters:
    * The function takes in a file path pointing to a single `.csv` file. 
    * The function also takes in a tuple of the index positions you expect the year data to be within the file path string. For example, in the path `folder/1996_data.csv` the tuple could either be (7, 11) or (-13, -9). 
2. Returns:
    * The function should return a **Pandas** DataFrame with the data from the `.csv` file, indexed on the year extracted from the file path.

Be sure to include a docstring with a brief description of the function (i.e. how it works, purpose) as well as identify the input parameters (i.e. type, description) and the returned output (i.e. type, description). Below is an example of how to format your docstring. 

```
def function(parameter1):
    """Description of function and
    what it does.
    
    Parameters
    ----------
    parameter1 : data_type_of_parameter1
        Description of parameter1
    
    Returns
    -------
    returned_data : data_type_of_returned_data
        Description of returned_data
    """
```

In [66]:
def import_csv(file_path, year_index):
    # YOUR CODE HERE
    """Imports csv and adds year from filepath as column

    Args:
        file_path (string): character string of file path locatio of csv
        year_index (tuple): index positions of the year within file path string

    Returns:
        dataframe: pandas dataframe
    """
    df = pd.read_csv(file_path)
    df["year"] = file_path[year_index[0]:year_index[1]]
    return df

In [67]:
# DO NOT MODIFY THIS CELL
import_works = False

# Create path to a single file as a test
single_file = os.path.join("earthpy-downloads",
                           "ca-fires-yearly",
                           "1992-2015-gt-100-acres",
                           "gt-100-acres-1993.csv")

try:
    output_df = import_csv(single_file, year_index=(-8, -4))
    # If the above is a dataframe, the line below should run
    output_df.columns
    print("\u2705 Great! Your 'import_csv' function returns a DataFrame! I didn't test that the dataframe also has a year column in it so please make sure it does have a year column to get full credit for this challenge when the autograder runs!")
    import_works = True
except NameError:
    print("\u274C Oops! Your import_csv function should return a dataframe. ")

✅ Great! Your 'import_csv' function returns a DataFrame! I didn't test that the dataframe also has a year column in it so please make sure it does have a year column to get full credit for this challenge when the autograder runs!

In [68]:
# DO NOT MODIFY THIS CELL

## Call Help on Your Custom Function

In the cell below, call help on your custom function to see what it returns. If you properly formatted the docstring, you should expect to see a very useful print out of the descriptive text you added in the docstring!

In [69]:
# YOUR CODE HERE
help(import_csv)

Help on function import_csv in module __main__:

import_csv(file_path, year_index)
    Imports csv and adds year from filepath as column

    Args:
        file_path (string): character string of file path locatio of csv
        year_index (tuple): index positions of the year within file path string

    Returns:
        dataframe: pandas dataframe

## Function Challenge 1: Use Your Function in a Workflow

Use a `for` loop to open and add the data in the directory:

`earthpy-downloads/ca-fires-yearly/monthly-fire-count`

to a new DataFrame following the same steps that you completed last week, but implementing your function.

1. loop through each `.csv` file sorted by name.
2. put the `.csv` file into your function and add the return from your function to a list. 
3. Outside of the for loop, combine all of the files into a single DataFrame and set the year column to be an index. 

Call the new DataFrame object at the end of the cell.

In [70]:
# YOUR CODE HERE
for_path = os.path.join(data_path, "earthpy-downloads", "ca-fires-yearly", "monthly-fire-count")

monthly_fire_count_files = glob(os.path.join(for_path, "*"))

monthly_fire_count_list = []
for file in monthly_fire_count_files:
    df = import_csv(file, [-8, -4])
    list.append(monthly_fire_count_list, df)

monthly_fire_count_df = pd.concat(monthly_fire_count_list)
monthly_fire_count_df

   Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec  year
0    0    2    2    3    7   19   33   89   37   22    3    2  1999
0    0    0    0    2    2   12   33   47   16   14    5    4  1998
0    1    0    1    0    9   16   31   22    7    4    3    0  2010
0    0    1    1    7   16   21   39   27   27    7    1    0  2004
0    0    0    0    2    5   28   47   27   43   15    4    0  2005
0    0    0    2    2   15   23   26   30   33    2    3    3  2011
0    3    1    8    4   21   23   31   30   11   25    3    0  2007
0    1    2    0    5   26   14   25   29    9    7    4    0  2013
0    0    1    0    1    7   25   31   43   15    3    1    0  2012
0    1    2    0    0   17   50   96   29   21   11    5    3  2006
0    0    4    7    3   19   42   34   21   20    6   11    0  2002
0    3    1    0    2    5   33   63   32   47   22    2    0  2003
0    0    3    0    8    2   17   57   29    9    5    1    1  2015
0    2    1    1    0   13   37   30   40   14    7    3    1  2001
0    0    0    3    3    5   19   31   22   17   10    0    3  2000
0    6    0    3    3    8   12   29   15   10    3    1    0  2014
0    0    1    1    4   13  159   39   31   13   17    3    0  2008
0    0    1    0    5   12   15   24   39   17    6    1    0  2009
0    0    1    0    0   11   25   53   35   25   25   11    3  1995
0    2    0    0    6    8   50   48   55   23    8    0    1  1994
0    2    0    1   15   39   64   64   93   25   26    3    1  1996
0    0    0    5    7   28   13   29   28   25    7    1    0  1997
0    0    0    0    2   27   44   33   30   23   17    9    2  1993
0    0    1    1    5   23   55   42   66   34    6    4    0  1992

In [71]:
# DO NOT MODIFY THIS CELL

<img style="float: left;" src="colored-bar.png"/>

## Function Challenge 2: Reuse Your Function

One of the benefits of functions is being able to use them in multiple areas of your code. Repeat the exercise above, but with the data in the fire size directory.

`earthpy-downloads/ca-fires-yearly/monthly-mean-size`

Once again, you will:

1. loop through each `.csv` file sorted by name.
2. put the `.csv` file into your function and add the return from your function to a list. 
3. outside of the for loop, combine all of the files into a single DataFrame and set the year column to be an index. 

Call the new `DataFrame` object at the end of the cell.

In [72]:
# YOUR CODE HERE
mean_size_path = os.path.join(data_path, "earthpy-downloads", "ca-fires-yearly", "monthly-mean-size")

monthly_mean_size_files = glob(os.path.join(mean_size_path, "*"))

monthly_mean_size_list = []
for file in monthly_mean_size_files:
    df = import_csv(file, [-8, -4])
    list.append(monthly_mean_size_list, df)

monthly_mean_size_df = pd.concat(monthly_mean_size_list)
monthly_mean_size_df

,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,year
0,0.00,0.0,0.00,134.00,198.00,254.75,780.62,1216.66,293.57,3556.57,229.20,246.50,1998
0,0.00,600.0,1325.00,537.67,2221.71,486.18,1138.27,4971.50,4813.05,4060.64,437.33,2560.50,1999
0,0.00,0.0,0.00,181.00,404.40,3348.07,1114.08,867.02,1160.56,922.67,1147.00,0.00,2005
0,0.00,0.0,622.50,206.25,333.71,719.35,1765.94,745.30,2400.79,1162.10,178.33,411.00,2011
0,107.00,0.0,130.00,0.00,657.63,410.69,2247.46,496.75,1625.00,438.25,145.33,0.00,2010
0,0.00,122.0,350.00,485.77,2134.06,999.71,2090.05,1764.45,975.22,9506.43,131.00,0.00,2004
0,0.00,200.0,0.00,143.00,1469.87,544.75,4999.86,12179.76,3011.24,214.17,350.00,0.00,2012
0,485.00,6699.5,0.00,0.00,577.70,892.61,4143.58,605.97,10769.00,4122.91,313.20,11442.17,2006
0,404.00,169.0,1116.25,882.50,613.10,1033.74,10025.75,565.37,12097.59,20224.88,2041.00,0.00,2007
0,335.00,353.5,0.00,183.94,3434.60,630.86,4021.00,11833.15,1432.44,228.29,1023.25,0.00,2013
0,389.33,12000.0,0.00,444.90,515.00,593.12,1474.28,2116.08,1302.91,34215.91,301.00,0.00,2003
0,0.00,2133.0,626.14,403.00,699.53,2661.50,7624.18,522.97,3745.00,493.33,750.00,0.00,2002
0,0.00,0.0,465.00,785.00,277.20,709.89,3826.20,3547.16,863.35,767.60,0.00,337.67,2000
0,806.50,0.0,203.33,826.67,3141.88,851.58,8337.06,9679.51,10195.63,1209.67,105.00,0.00,2014
0,0.00,2417.0,0.00,1081.00,270.50,4577.18,8862.38,2815.68,16728.00,413.00,323.00,1288.00,2015
0,5254.00,2400.0,200.00,0.00,755.77,873.04,1144.33,4941.70,2349.50,1369.00,194.00,1200.00,2001
0,0.00,945.0,0.00,778.60,1226.25,707.14,1224.74,8838.82,1347.76,2158.75,145.00,0.00,2009
0,0.00,400.0,680.00,489.00,1949.62,6863.29,3264.13,2171.58,1681.31,1736.82,14489.00,0.00,2008
0,280.00,0.0,0.00,936.33,1255.88,1364.48,1889.24,2549.96,2755.83,535.63,0.00,250.00,1994
0,0.00,160.0,0.00,0.00,400.82,1307.80,885.64,1798.83,480.62,1250.06,362.73,179.33,1995
0,0.00,0.0,406.00,423.00,2277.00,896.69,580.17,4648.29,1050.31,7302.14,375.00,0.00,1997
0,1940.00,0.0,1000.00,3892.93,798.95,1044.02,827.98,4020.10,438.60,3070.85,134.67,150.00,1996
0,0.00,120.0,1800.00,1390.80,402.94,444.69,436.17,2255.88,1684.85,321.67,283.00,0.00,1992
0,0.00,0.0,0.00,250.50,923.37,1003.02,444.08,804.40,2159.65,7375.48,1451.91,240.00,1993

In [73]:
# DO NOT MODIFY THIS CELL

<img style="float: left;" src="colored-bar.png"/>

## Function Challenge 3: Create a Function The Loops Through A Directory Of .csv Files

You may have noticed that a lot of the code that you use to loop through the directories 
and open `.csv` files is repeated. You can also make that entire loop workflow into a 
function that calls the function that you wrote above to open a `.csv` file. In the cell below create a function with the following properties.

1. Parameters:
    * The function takes in an unsorted list of `.csv` files (such as the output from a `glob` operation).
    * The function also takes in a tuple of the index positions you expect the year data to be within the file path string. For example, in the path `folder/1996_data.csv` the tuple could either be (7, 11) or (-13, -9). 
2. Returns:
    * The function should return a **Pandas** DataFrame that contains all of the data stored within that folder, and is indexed on the year column with the data you extracted from the file path. 
3. Other Requirements:
    * The function should call your previous function to open up the individual `.csv` files inside the `for` loop. 
    * Your function needs a numpy-style docstring following the same format outlined above for your first function.

In [74]:
def process_csv_files(file_path_list, year_index):
    """Function takes list of file paths and index of year in file names and imports csvs

    Args:
        file_path_list (_type_): list of filepaths
        year_index (_type_): index of year in file name

    Raises:
        NotImplementedError: Error

    Returns:
        _type_: dataframe of concatenated csv files
    """
    list_of_dfs = []

    for file in file_path_list:
        df = import_csv(file, year_index)
        list.append(list_of_dfs, df)
        
    concat_df = pd.concat(list_of_dfs)
    concat_df.set_index("year")
    
    
    return concat_df
    raise NotImplementedError()

In [75]:
# DO NOT MODIFY THIS CELL
process_function_points = 0
process_works = True
single_dir = os.path.join("earthpy-downloads",
                          "ca-fires-yearly",
                          "1992-2015-gt-100-acres")

two_files = sorted(glob(os.path.join(single_dir, "*.csv")))[0:2]
two_files

try:
    out_df = process_csv_files(two_files, (-8, -4))
    out_df.columns
    process_works = True
    print("\u2705 Function 'process_csv_files' returns a dataframe!")
    process_function_points += 5
    if len(out_df) == 424:
        print("\u2705 Great! It looks like your function combines csv files correctly!")
        process_function_points += 5
    else:
        print("\u274C The function doesn't seem to combine csv files correctly.")

except:
    print("\u274C Oops! It looks like your function doesn't return a dataframe.")

print("\n \u27A1 You received {} out of 10 points for your function being defined properly. Please check that it also returns a year column.".format(
    process_function_points))
process_function_points

✅ Function 'process_csv_files' returns a dataframe!
✅ Great! It looks like your function combines csv files correctly!

 ➡ You received 10 out of 10 points for your function being defined properly. Please check that it also returns a year column.

10

## Call Help on your Custom Function

In the cell below, call help on your custom function to see what it returns.

In [76]:
# YOUR CODE HERE
help(process_csv_files)

Help on function process_csv_files in module __main__:

process_csv_files(file_path_list, year_index)
    Function takes list of file paths and index of year in file names and imports csvs

    Args:
        file_path_list (_type_): list of filepaths
        year_index (_type_): index of year in file name

    Raises:
        NotImplementedError: Error

    Returns:
        _type_: dataframe of concatenated csv files

<img style="float: left;" src="colored-bar.png"/>

## Function Challenge 4: Create a DataFrame Using Your Function

In the cell below, use `glob` to get all of the `.csv` files from 

`earthpy-downloads/ca-fires-yearly/1992-2015-gt-100-acres`

Put your **unsorted** output from glob into your function and output the combined `DataFrame`.

Call the output from your function the end of the cell.

In [77]:
# YOUR CODE HERE
files = glob(os.path.join(data_file_path, "1992-2015-gt-100-acres", "*"))

df = process_csv_files(files, [-8, -4])

df

,fd_unq_id,source_reporting_unit_name,fire_name,month,month_num,cause,fire_size,fire_size_class,state,county,year
0,15000792,CDF - Riverside Unit,RIVER,February,2,Missing/Undefined,122.0,D,CA,Riverside,2004
1,15001254,San Bernardino National Forest,UPPER SANTA ANA BURN ESCAPE,March,3,Missing/Undefined,350.0,E,CA,San Bernardino,2004
2,317618,Bakersfield District,FORT,April,4,Arson,150.0,D,CA,Inyo,2004
3,1311320,CDF - Merced-Mariposa Unit,RIMS FIRE,April,4,Miscellaneous,200.0,D,CA,NaN,2004
4,1311367,CDF - Merced-Mariposa Unit,210,April,4,Equipment Use,115.0,D,CA,NaN,2004
...,...,...,...,...,...,...,...,...,...,...,...
115,1300492,Dunnigan Fire Protection District,SIX,October,10,Missing/Undefined,1235.0,F,CA,Yolo,2009
116,300341742,San Mateo-Santa Cruz Unit,LOMA IC,October,10,Missing/Undefined,490.5,E,CA,NaN,2009
117,1332172,Humboldt-Del Norte Unit,IAQUA,October,10,Equipment Use,160.0,D,CA,NaN,2009
118,300331819,Humboldt-Del Norte Unit,CCSO,October,10,Missing/Undefined,250.0,D,CA,NaN,2009
119,15000493,Orange County Fire Department,ORTEGA,November,11,Missing/Undefined,145.0,D,CA,Orange,2009

In [78]:
# DO NOT MODIFY THIS CELL

<img style="float: left;" src="colored-bar.png"/>

## Function Challenge 5 - Loop Through Nested Directories 

In the next section of this assignment, you will implement functions 
using a set of nested directories. To begin, download the data needed 
from **this url: https://ndownloader.figshare.com/files/21894528** using earthpy
in the cell below.

In [79]:
# YOUR CODE HERE
myurl = "https://ndownloader.figshare.com/files/21894528"

data_path_ch5 = et.data.get_data(url = myurl)
data_path_ch5

'/Users/judith/earth-analytics/data/earthpy-downloads/avg-monthly-temp-fahr'

## Loop Through Nested Directories

Sometimes you have a nested data directory structure that you need to process. 

The data you just downloaded contains a folder named `avg-monthly-temp-fahr` which 
holds two other folders, `San-Diego` and `Sonoma`. Those folders contain `.csv` 
files for each year from 1999 to 2003 that has the monthly maximum temperature for 
each location. 

Write a function that accepts the path to the parent folder, `avg-monthly-temp-fahr`, 
and creates a single **Pandas** DataFrame with all the data in both the `San-Diego` 
and `Sonoma` folders for monthly maximum temperature. The year and the location (Sonoma 
vs. San-Diego) should be added as new columns in the `DataFrame` using the year
in the file name and the location in each directory.

In the cell below create a function with the following properties.

1. Parameters:
    * The function takes in folder name to be looped through.
    * The function also takes in a tuple of the index positions you expect the year data to be within the file path string. For example, in the path `folder/1996_data.csv` the tuple could either be (7, 11) or (-13, -9). 
2. Returns:
    * The function should return a **Pandas** DataFrame that contains all of the data stored within that folder, and is indexed on the year column with the data you extracted from the file path. 
3. Other Requirements:
    * The function should use the function that you created above (`process_csv_files()` takes in a list of files to open in a for loop. 
    * Your function needs a numpy-style docstring

In [118]:
def process_nested_csv_files(folder_name, year_index):
    # YOUR CODE HERE
    """takes in parent folder loops through nested directories, combines all csv's into df, uses year and location as colum

    Args:
        folder_name (_type_): parent folder
        year_index (_type_): index of year in file name
    """
    locations = os.listdir(folder_name)
    loc_list = []
    for loc in locations:
        files = glob(os.path.join(folder_name, loc, "*"))
        loc_df = process_csv_files(files, year_index)
        loc_df["location"] = loc
        list.append(loc_list, loc_df)
    
    df = pd.concat(loc_list)
    df = df.set_index("year")

    return df

In [111]:
# DO NOT MODIFY THIS CELL

nested_function_points = 0
nested_works = False

a_dir = os.path.join(
    "earthpy-downloads",
    "avg-monthly-temp-fahr")

try:
    out_df_challenge_5 = process_nested_csv_files(a_dir, (-8,-4))
    out_df_challenge_5.columns
    nested_works = True
    print("\u2705 Great your function 'process_nested_csv_files' returns a dataframe!")
    nested_function_points += 5
except NameError:
    print("\u274C Oops, make sure your function returns a dataframe or something else went wrong.")

print("\n \u27A1 You received {} out of 5 points for your function being defined properly.".format(
    nested_function_points))
nested_function_points

✅ Great your function 'process_nested_csv_files' returns a dataframe!

 ➡ You received 5 out of 5 points for your function being defined properly.

5

## Call Help on your Custom Function

In the cell below, call help on your custom function to see what it returns.

In [112]:
# YOUR CODE HERE
help(process_nested_csv_files)

Help on function process_nested_csv_files in module __main__:

process_nested_csv_files(folder_name, year_index)
    takes in parent folder loops through nested directories, combines all csv's into df, uses year and location as colum

    Args:
        folder_name (_type_): parent folder
        year_index (_type_): index of year in file name

<img style="float: left;" src="colored-bar.png"/>

## Function Challenge 6: Create a Combined DataFrame with your Function

Run your function on the `avg-monthly-temp-fahr` folder that was downloaded earlier. This should return a **pandas** DataFrame that has all the data from both folders in it, as well as the index set to the year and the location added as a new column to the DataFrame.
 
Call the output from your function the end of the cell.

In [119]:
# YOUR CODE HERE
ch6_output = process_nested_csv_files(data_path_ch5, (-13, -9))
ch6_output

,Year,January,February,March,April,May,June,July,August,September,October,November,December,location
year,,,,,,,,,,,,,,
2002,2002,63.0,66.2,63.6,63.7,66.1,68.7,71.8,73.4,75.5,68.4,71.4,63.7,San-Diego
2003,2003,71.4,64.6,66.5,65.2,66.9,67.4,74.3,77.5,74.0,73.1,67.4,64.6,San-Diego
1999,1999,65.2,64.9,63.6,64.6,64.4,66.9,72.7,72.7,71.4,77.7,67.4,67.6,San-Diego
2001,2001,62.2,61.7,63.7,63.6,67.5,72.0,73.0,73.5,73.2,71.1,66.9,63.3,San-Diego
2000,2000,65.8,65.3,63.7,67.7,69.1,72.4,73.5,76.3,75.5,69.5,66.0,66.9,San-Diego
2000,2000,56.8,58.0,64.8,69.5,75.0,79.5,81.4,83.7,83.4,71.8,60.7,58.5,Sonoma
2001,2001,56.5,58.4,68.0,66.7,83.1,86.1,81.2,85.3,81.0,78.4,64.0,55.6,Sonoma
1999,1999,56.1,56.6,58.7,68.3,72.7,80.6,80.9,82.9,81.3,79.1,64.2,61.5,Sonoma
2003,2003,58.9,61.8,66.4,61.5,74.2,81.1,87.0,83.5,85.0,82.7,61.0,56.4,Sonoma
2002,2002,55.8,62.9,63.5,66.9,74.5,84.2,82.8,82.1,84.5,75.7,67.6,57.4,Sonoma

In [120]:
# DO NOT MODIFY THIS CELL

## Pep 8, Spelling and Does the Notebook Run?
In this cell, we will give you points for the following

1. PEP 8 is followed throughout the notebook (4 points)
2. Spelling and grammar are considered in your written responses above (4 points)
3. The notebook runs from top to bottom without any editing (it is reproducible) - 4 points